# Generated by Django 6.0.3 on 2026-04-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_district_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='custom_id',
            field=models.IntegerField(editable=False),
        ),
    ]
