# Generated by Django 6.0.3 on 2026-04-15 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="expires_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
