# Generated by Django 6.0.3 on 2026-04-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_mfa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_secret",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
