# Generated by Django 6.0.3 on 2026-04-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_is_mfa_enabled_user_mfa_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role_level",
            field=models.CharField(default="catering_boy", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="total_jobs",
            field=models.IntegerField(default=0),
        ),
    ]
