# Generated by Django 6.0.3 on 2026-04-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_role_level_user_total_jobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
