# Generated by Codex on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_fcm_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("worker", "Worker"),
                    ("company", "Company"),
                    ("admin", "Admin"),
                ],
                max_length=10,
            ),
        ),
    ]
