# Generated by Django 6.0.3 on 2026-04-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="attendance",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("present", "Present"),
                    ("absent", "Absent"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
