# Generated by Codex on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_booking_reminder_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="salary",
            field=models.IntegerField(default=0),
        ),
    ]
