# Generated by Codex on 2026-04-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_booking_rating_booking_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="booking.booking",
            ),
        ),
    ]
