# Generated by Django 6.0.3 on 2026-04-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="position",
            field=models.CharField(
                choices=[
                    ("juicer", "Juicer"),
                    ("juicer_helper", "Juicer Helper"),
                    ("catering_boy", "Catering Boy"),
                    ("main_boy", "Main Boy"),
                    ("supervisor", "Supervisor"),
                    ("captain", "Captain"),
                    ("chef_helper", "Chef Helper"),
                    ("decoration", "Decoration"),
                ],
                max_length=50,
            ),
        ),
    ]
