# Generated by Django 6.0.3 on 2026-04-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_alter_slot_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="salary",
            field=models.IntegerField(default=0),
        ),
    ]
