# Generated by Django 6.0.3 on 2026-04-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="receiver_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="receiver_role",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
